routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::Resource('books' , 'BookController')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
class Book extends Model
{
 //database fields to be allwed for massive assigment
 protected $fillable =[
    'title','author', 'status',
];

    /**
     * Get the user that owns the books.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Book;
class User extends Authenticatable
{

/**
     * Get the user his  books.
     */
    public function books()
    {
        return $this->hasMany('App\Book');
    }

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

use App\Book;
use App\User;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$id=1;
        $id=Auth::id();
        if (Gate::denies('manager')) {
            $boss = DB::table('employees')->where('employee',$id)->first();
            $id = $boss->manager;
        }
        $books =User::find($id)->books;
        return view('book.index' , compact('books'));

        //return view('book.index'  , ['books'=>$books]);
  
 




    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Gate::denies('manager')) {
            abort(403,"Sorry you are not allowed to create books..");
        }
 
       return view('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Gate::denies('manager')) {
            abort(403,"Are you a hacker or what?");
       }
        $book=new Book();
        //$id = 1;
        $id=Auth::id();//the idea of the current user
        $book->title=$request->title;
        $book->user_id=$id;
        $book ->author=$request->author;
        $book->created_at =now()->toDateTimeString();;
        $book->status=0;
        $book->save();
        return redirect('books');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Gate::denies('manager')) {
            abort(403,"Are you a hacker or what?");
       }
       $book = Book::find($id);
       $id = Auth::id(); //the idea of the current user
        return view('book.edit' , compact('book'));

        
     
 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //only if this todo belongs to user
       $book = Book::findOrFail($id);
       //employees are not allowed to change the title 
        if (Gate::denies('manager')) {
            if ($request->has('title'))
                   abort(403,"You are not allowed to edit books..");
        }   
         //make sure the todo belongs to the logged in user
       if(!$book->user->id == Auth::id()) return(redirect('books'));
  
       //test if title is dirty
      
       $book->update($request->except(['_token']));
  
       if($request->ajax()){
           return Response::json(array('result' => 'success1','status' => $request->status ), 200);   
       } else {          
           return redirect('books');           
       }

        // $book = Book::find($id);
        // $book -> update($request->all());
        //  return redirect('books');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Gate::denies('manager')) {
            abort(403,"Are you a hacker or what?");
       }
        $book = Book::find($id);
        #we can right also $book -> delete($id);
        $book -> delete();
        $id = Auth::id(); //the idea of the current user
        $book->title = $request->title;
        $book->user_id = $id;
        $book->status = 0;
        $book->save();
        return redirect('books');

      
      
 
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/book/Index.blade.php
@extends('layouts.app')
@section('content')

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<div class='container'>
    <br/><br/>
      <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
              <th scope="col">id</th>
              <th scope="col">Book title</th>
              <th scope="col">Author name</th>
              <th scope="col">Created at</th>
              <th scope="col">Updated at</th>
              <th scope="col">Status</th>
       


            </tr>
          </thead>
      
          <tbody>
          @foreach($books as $book)
            <tr>
                <td><a href = "{{route('books.edit' , $book->id)}}">{{$book->id}} </td>
                <td><a href = "{{route('books.edit' , $book->id)}}">{{$book->title}}</td>
                <td>{{$book->author}}</td>
                <td>{{$book->created_at}}</td> 
                <td>{{$book->updated_at}}</td>
                <td>{{$book->status}}
                @if ($book->status)
                <input type = 'checkbox' id ="{{$book->id}}" checked>
                @else
               <input type = 'checkbox' id ="{{$book->id}}">
               @endif  
                </td>
            </tr>
            @endforeach

          </tbody>
      </table>
          <div class ="container">
        <div class="col-0  offset-0">
           <a href="{{route('books.create')}}" class=" btn btn-secondary">Add a book to your list</a>
       </div>
       @can('manager')
       <a href="{{route('books.create')}}">Create New todo </a>
       @endcan
</div>
@endsection


<script>
       $(document).ready(function(){
           $(":checkbox").click(function(event){
               $.ajax({
                   url: {{url('books')}} + '/' + event.target.id ,
                   dataType:'json' ,
                   type:'put',
                   contentType:'application/json',
                   data: JSON.stringify{'status':event.target.checked, _token:'{{csrf_token()}}'},
                   processData:false,
                   success: function( data){
                        console.log(JSON.stringify( data ));
                   },
                   error: function(errorThrown ){
                       console.log( errorThrown );
                   }
               });               
           });
       });
   </script>  

resources/views/book/create.blade.php
@extends('layouts.app')
@section('content')

<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<div class="container">
    <br/><br/>
    <h3> Add a new books to your list</h3>
        
           

    <form method="post" action ="{{action('BookController@store')}}">
            {{csrf_field()}}
            <div class="form-group">
                <label for="title">Please enter the name of the requested book :</label>
                <input type ="text" class ="form-control" name="title">
            </div>
            <div class="form-group">
                <label for="title">What is the author's name?</label>
                <input type ="text" class ="form-control" name="author">
            </div>
            
            <div class ="container">
                <div class="col-4  offset-4">
                     <input type ="submit" class="form-control btn btn-secondary" name="submit" value ="Create"> 
                </div>
            </div> 
        <br><br>
        <div class ="container">
            <div class="col-4  offset-4">
                <a href="{{route('books.index')}}" class=" form-control btn btn-secondary">Back to list</a>
            </div>
        </div>
  </div>

    </form>
</div>

@endsection

resources/views/book/edit.blade.php
@extends('layouts.app')
@section('content')

<head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        </head>
     <!--Update-->

        <div class="container">
            <br/><br/>
            <h3>Edit Book</h3>
         
            
            <form method="post" action ="{{action('BookController@update' , $book->id)}}">
                {{csrf_field()}}
                @method('PATCH')
                    <div class="form-group">
                        <label for="title">Book to update</label>
                        <input type ="text" class ="form-control" name="title" value = "{{$book->title}}">
                    </div>
                   
                    <div class="form-group">
                        <label for="title">Author to update</label>
                        <input type ="text" class ="form-control" name="author" value = "{{$book->author}}">
                    </div>

                    
                    <br>
                    <div class ="container">
                        <div class="col-4  offset-4">
                            <input type ="submit" class="form-control btn btn-secondary" name="submit" value =" save "> 
                        </div>
                    </div>
            </form>
        </div>
        
        
        <!--Delete-->

        <br><br>
        <form method="post" action ="{{action('BookController@destroy' , $book->id)}}">
            {{csrf_field()}}
            @method('DELETE')
            <div class ="container">
                <div class="col-4  offset-4">
                    <input type ="submit" class="form-control btn btn-secondary" name="submit" value ="Delete"> 
                </div>
            </div>
        
        </form>
        <br><br>
        <form>
        
                <div class ="container">
                    <div class="col-4  offset-4">
                        <a href="{{route('books.index')}}" class=" form-control btn btn-secondary">Back to list</a>
                    </div>
                </div>
        </form>

        @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/books') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>